Git lecture03
goat0325/RaiseTech pull request #2
Opened 2024-01-16 12:35 UTC by goat0325

# 第3回課題提出
掲題の件確認お願いいたします。

2024-01-17 04:16 UTC, MasatoshiMizumoto commented on lecture02.md
このファイルが含まれているのは前回のレビュー後のGit対応が間違っている、漏れていると思われます！

2024-01-17 15:10 UTC, goat0325 commented on lecture02.md
訂正いたしました。再度確認お願いいたします。

2024-01-18 01:19 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-01-18 01:19 UTC, MasatoshiMizumoto commented on lecture03.md
> +###　課題参考画像
見出しのスタイルが崩れてます！

2024-01-18 01:19 UTC, MasatoshiMizumoto commented on lecture03.md
> +* <img width="489" alt="スクリーンショット 2024-01-14 1 52 32" src="https://github.com/goat0325/RaiseTech/assets/147507987/5b1d5269-6c64-4254-8926-5765f2fc2394">
この方法だとGitHubを使うのを止めて他社Gitサービスに移動したら見られなくなるので、
バージョン管理に含めて内部リンクで実装お願いします！！

2024-01-18 05:19 UTC, merged

2024-01-18 05:45 UTC, goat0325 commented on lecture03.md
> +* <img width="489" alt="スクリーンショット 2024-01-14 1 52 32" src="https://github.com/goat0325/RaiseTech/assets/147507987/5b1d5269-6c64-4254-8926-5765f2fc2394">
修正してみました。確認お願いいたします。