Lecture10
goat0325/RaiseTech pull request #7
Opened 2024-03-15 09:20 UTC by goat0325

第10回課題を提出させていただきます。
ご確認よろしくお願いいたします。

2024-03-15 13:55 UTC, MasatoshiMizumoto requested changes
テンプレートもレビューしたいのでaddお願いします！！

2024-03-15 14:29 UTC, goat0325 commented
テンプレートもaddさせていただきました。
それぞれの項目の題目の下に添付しております。
再度ご確認お願いいたします。

2024-03-15 15:23 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-03-15 15:23 UTC, MasatoshiMizumoto commented on img/lecture10/test10-RDS.yml
ファイルの終端エラーマークが出ているので対応お願いします！！

2024-03-15 15:23 UTC, MasatoshiMizumoto commented on img/lecture10/codebuild-vpc-cfn.yaml
このファイルはデプロイに使ってますか？？

2024-03-16 03:52 UTC, goat0325 commented
ご指摘ありがとうございました！
ファイル削除と、終端のエラー解除できたかと思いますので、
もう一度ご確認お願いいたします。

2024-03-16 04:50 UTC, MasatoshiMizumoto requested changes
ご対応お願いします！！

2024-03-16 04:50 UTC, MasatoshiMizumoto commented on img/lecture10/test10-RDS.yml
まだ出てますのでよろしくお願いします！
解消できたかの確認方法がわからないなら先に調べていただけますと！

2024-03-16 05:58 UTC, goat0325 commented
commitsから終端のエラーマークが無くなっている事を確認しました。
ご確認お願いいたします。

2024-03-16 06:26 UTC, MasatoshiMizumoto approved these changes
LGTMです！
![LGTM](https://lgtmoon.herokuapp.com/images/18400)

2024-03-16 06:29 UTC, merged